set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#EEDFD3 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#EEDFD3 guibg=#161618 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#3E4860 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CmpItemAbbr guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CmpItemAbbrDeprecated guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight CmpItemAbbrMatch guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight CmpItemAbbrMatchFuzzy guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight CmpItemKind guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CmpItemMenu guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=NONE guibg=#202022 guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#9C8D81 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#BBA2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#3E4860 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#161618 guibg=#EEDFD3 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#202022 guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#DEC7B5 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#BBA2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#3A405A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor0 guifg=#414144 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor1 guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor10 guifg=#6E3F59 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor11 guifg=#4E647E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor12 guifg=#5D7298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor13 guifg=#607B9A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor14 guifg=#CF8C59 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor15 guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor2 guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor3 guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor4 guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor5 guifg=#596E88 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor6 guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor7 guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor8 guifg=#9C8D81 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DevColor9 guifg=#363B59 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#9A6842 guibg=NONE guisp=#9A6842 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#45576E guibg=NONE guisp=#45576E blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#5A6A8C guibg=NONE guisp=#5A6A8C blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#596E88 guibg=NONE guisp=#596E88 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#596E88 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#60394F guibg=#1A1320 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#5F4F44 guibg=#1B1B1D guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#343851 guibg=#131420 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#343851 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#5A6A8C guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#60394F guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#5A6A8C guibg=#171926 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#EEDFD3 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#343851 guibg=#DEC7B5 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#343851 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#3E4860 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#5A6A8C guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#DEC7B5 guibg=#151723 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight GitGutterAdd guifg=#60394F guibg=#161618 guisp=NONE blend=NONE gui=bold
highlight GitGutterChange guifg=#5A6A8C guibg=#161618 guisp=NONE blend=NONE gui=bold
highlight GitGutterChangeDelete guifg=#BBA2C3 guibg=#161618 guisp=NONE blend=NONE gui=bold
highlight GitGutterDelete guifg=#343851 guibg=#161618 guisp=NONE blend=NONE gui=bold
highlight Identifier guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#9C8D81 guibg=#634940 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#EEDFD3 guibg=#161618 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#BBA2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#CAB3A0 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#EEDFD3 guibg=#604C43 guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#9C8D81 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#5A6A8C guibg=NONE guisp=#CAB3A0 blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#EEDFD3 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#3A405A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#3A405A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#DEC7B5 guibg=#151723 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#DEC7B5 guibg=#151723 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#45576E guibg=#151723 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#766960 guibg=#1B1B1D guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#161618 guibg=#9A6842 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#161618 guibg=#5A6A8C guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#161618 guibg=#60394F guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#161618 guibg=#BBA2C3 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#161618 guibg=#343851 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#161618 guibg=#3E4860 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#9C8D81 guibg=#3E4860 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#CAB3A0 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#60394F guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#DEC7B5 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#766960 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#DEC7B5 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#CAB3A0 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#343851 guibg=#DEC7B5 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#3E4860 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#EEDFD3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#DEC7B5 guibg=#22161D guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#EEDFD3 guibg=#5A6A8C guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#766960 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#EEDFD3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#CAB3A0 guibg=#5F4F44 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#766960 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#3A405A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#9A6842 guibg=NONE guisp=#9A6842 blend=NONE gui=underline
highlight SpellCap guifg=#5A6A8C guibg=NONE guisp=#5A6A8C blend=NONE gui=underline
highlight SpellLocal guifg=#596E88 guibg=NONE guisp=#596E88 blend=NONE gui=underline
highlight SpellRare guifg=#45576E guibg=NONE guisp=#45576E blend=NONE gui=underline
highlight Statement guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#DEC7B5 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#766960 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#6E3F59 guibg=#60394F guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#4E647E guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#BBA2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#CAB3A0 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#CAB3A0 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#60394F guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TelescopeBorder guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TelescopeMatching guifg=#4E647E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TelescopeMultiSelection guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=bold
highlight TelescopePromptBorder guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TelescopePromptCounter guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TelescopeSelection guifg=#CF8C59 guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight TelescopeSelectionCaret guifg=#CF8C59 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#45576E guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#DEC7B5 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight VirtColumn guifg=#151723 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Visual guifg=#161618 guibg=#635145 guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WhichKey guifg=#B07898 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WhichKeyDesc guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WhichKeyFloat guifg=NONE guibg=#414144 guisp=NONE blend=NONE gui=NONE
highlight WhichKeyGroup guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WhichKeySeparator guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WhichKeySeperator guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WhichKeyValue guifg=#CAB3A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#EEDFD3 guibg=#5A6A8C guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#DEC7B5 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#766960 guibg=#161618 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#3A405A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#EEDFD3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#BBA2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#BBA2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#BBA2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @markup.italic guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @markup.link guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight! link @markup.link.label @markup.link
highlight! link @markup.link.url @markup.link
highlight @markup.list guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @markup.strikethrough guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @markup.strong guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @markup.underline guifg=#DEC7B5 guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @method guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @neorg.definitions.content.norg guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @neorg.definitions.title.norg guifg=#CF8C59 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @neorg.headings.1.title.norg guifg=#CF8C59 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @neorg.headings.2.title.norg guifg=#607B9A guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @neorg.headings.3.title.norg guifg=#5D7298 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @neorg.headings.4.title.norg guifg=#4E647E guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @neorg.headings.5.title.norg guifg=#6E3F59 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @neorg.headings.6.title.norg guifg=#363B59 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @neorg.markup.verbatim.norg guifg=#BB9A81 guibg=#232324 guisp=NONE blend=NONE gui=NONE
highlight @neorg.quotes.1.content.norg guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @neorg.quotes.2.content.norg guifg=#596E88 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @neorg.quotes.3.content.norg guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @neorg.quotes.4.content.norg guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @neorg.quotes.5.content.norg guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @neorg.quotes.6.content.norg guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#EEDFD3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#EEDFD3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#EEDFD3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#CF8C59 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#3A405A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#60394F guibg=#9C8D81 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#343851 guibg=#9C8D81 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#BBA2C3 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#60394F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#9A6842 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#45576E guibg=#9C8D81 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#9C8D81 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#5A6A8C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#45576E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#343851 guibg=NONE guisp=NONE blend=NONE gui=NONE
